### PR TITLE
Support non-ascii header id

### PR DESCRIPTION
**Pull request by fengmk2**
```md
## non-ascii 中文
```

=>

```html
<h2 id="non-ascii-%E4%B8%AD%E6%96%87">non-ascii 中文</h2>
```

### CODE REVIEW

**Comment by AaronO** [comment]
@fengmk2 This makes a lot of sense, and thanks for the tests :+1: 

LGTM

**Comment by fengmk2** [comment]
Good! @AaronO hope gitbook use the new version of kramed.

**Comment by AaronO** [comment]
@fengmk2 Yep https://github.com/GitbookIO/gitbook/commit/b50dea9c70f952a3886c8846796340a211868021 ;)

**Comment by AaronO** [comment]
I'll get that into production later today.

**Comment by fengmk2** [comment]
Thanks! I will try it right now!

**Pull request merged**
